# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
      - main
      - master
    tags:
      - "*"
  pull_request:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script      
        env:
          REFRENCE: ${{ github.ref_name }}
          EVENT_NAME: ${{ github.event_name }}
          REF_TYPE: ${{ github.ref_type }}
        run: |
          if [[ "${REF_TYPE}" != "tag" ]]; then
            export REFRENCE=$(git rev-parse --abbrev-ref HEAD) # if ran by PR, it wil set the tag to the branch name
          fi
          echo "::notice title=REFRENCE:: $REFRENCE"
          echo "::notice title=EVENT_NAME:: $EVENT_NAME"
          echo "::notice title=REF_TYPE:: $REF_TYPE"
          branch=$(git rev-parse --abbrev-ref HEAD)
          echo "::notice title=Current branch is $branch:: nothing to see here"
